# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e275559bc2ee3e5c55ca5bcfd05cef3b341202da728a0c938fc807bfd0528ec1f89fa61d32718e8ceb57867de92c612524137e77d437eee4ee1d4d9246b889e7

test:
  secret_key_base: 5b7c9828087a775e1d345dd07963870e9c555fc3b6a6e16ffe347bbac019eb1ebd0c2fc1d5c2722cc3962f01812ac833089eb3620a419b39eaf1b1e1666d90bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
